# Generated by Django 5.2.7 on 2025-10-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event title', max_length=200)),
                ('date', models.DateField(blank=True, help_text='Event date', null=True)),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=500)),
                ('slug', models.SlugField(help_text='Unique slug for public access', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(help_text="Driver's name", max_length=100)),
                ('car_name', models.CharField(blank=True, help_text='Car name/label', max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Number of seats available', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Member's name", max_length=100)),
                ('contact', models.CharField(blank=True, help_text='Contact information (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, help_text='Assigned car', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='events.car')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('event', 'name')},
            },
        ),
    ]
